apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkedin-collector
  namespace: {{ namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkedin-collector
  template:
    metadata:
      labels:
        app: linkedin-collector
        # Replace pods on every deployment https://github.com/helm/helm/issues/5696
        date: "{{ now }}"
    spec:
      containers:
      - name: collector
        image: {{ image.registry }}/{{ image.repository }}:{{ image.tag }}
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: collector-config
#          - secretRef:
#              name: collector-secrets
        volumeMounts:
        - name: state-storage
          mountPath: /state
      volumes:
      - name: state-storage
        persistentVolumeClaim:
          claimName: state