apiVersion: v1
kind: Service
metadata:
  name: linkedin-collector
  namespace: {{ namespace }}
spec:
  selector:
    app: linkedin-collector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
